### PR TITLE
Fix rejected handgrade

### PR DESCRIPTION
**Pull request by Normanwqn**
@james-perretta  Would you mind taking a look once you get some time? Thanks.

Addressing [this issue](https://github.com/eecs-autograder/autograder.io/issues/31)

<b> Before:</b>
image

<b> After </b>
image
Screenshot 2024-04-17 at 14 32 30

Instead of showing `ungraded` for the handgrading status of student group whose submissions were all rejected, the UI would now determine the status by checking whether there is a submission that is counted towards the submission limit. If the student group does not have a submission that count towards the limit, the UI would indicate the handgrading status as "No Valid Submission" and not clickable.

As demonstrated, this fix has been tested on a real student submission. We may introduce additional unit/regression tests if needed in future.

### CODE REVIEW

**Comment by james-perretta** [comment]
@Normanwqn I'm afraid we've all been tricked by this one. While your solution of checking `num_submits_towards_limit` is nice and simple, I don't think that will quite work because that value resets every 24 hours.

Instead, I think a fix for this would require a change to the API endpoint that loads all handgrading results. Specifically, we'd need to count the number of submissions with `finished_grading` status and include that in the API response. The simplest way to do that would be to change the prefetch queryset [here](https://github.com/eecs-autograder/autograder-server/blob/develop/autograder/handgrading/views/handgrading_result_views.py#L370) (the API docs would need some updating in this case, as the description for `num_submissions` in this context would be inaccurate). This would also fix the issue for groups with only "removed from queue" and "error" submissions. 

I'm guessing it's too close your assignment deadline to switch gears on this? Regardless, I appreciate your work on this, and now we have a better sense of the issue and how to resolve it.

**Comment by broad-well** [comment]
I added a new property named `has_autograded_submissions` without changing the prefetch queryset in the commit referenced above. Should the queryset still be changed?

**Comment by james-perretta** [comment]
@broad-well See my comment on that commit you referenced. 

Side note: After adding the new field, we'll need to update the type definitions in ag-client-typescript and then update the package here. I can take care of the ag-client-typescript update once we get the API change ironed out.

**Comment by Normanwqn** [comment]
@james-perretta  Added [commit](https://github.com/broad-well/autograder-server/commit/391569366dd3d30d846f7df034365a6cb73d73a7) to change  `finished_grading_results_exist` to use `any` generator.

I will change the frontend accordingly

**Comment by Normanwqn** [comment]
@james-perretta 

Thank you for your help so far.
We have also added some [test cases](https://github.com/broad-well/autograder-server/commit/4fcaab2c77b401bcf1df10390888cbc3b79bd952) for the API change on the backend. 

The deadline for EECS 481 is on Friday. It is likely that we won't have time to get fixing the entirety of the issue before the deadline, but I am willing to help out afterwards.

**Comment by james-perretta** [comment]
@Normanwqn Thanks, and sounds good! Can you open a PR in the autograder-server repo when you get a chance?

**Comment by Normanwqn** [comment]
@james-perretta 
I opened [a PR on the server side](https://github.com/eecs-autograder/autograder-server/pull/680).

**Comment by james-perretta** [comment]
Thanks! I will review these tomorrow

**Pull request merged**
